- docs/AboutUs.md
> Update Si Rui's About Us

- docs/AboutUs.md
> Update My's AboutUs.md

- src/main/java/seedu/address/model/person/Company.java
- src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
Change the `find` command to also search for the newly added field `Company`.
Update the tests for `find` command.
Fixes #39
> Update the function of find command

- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Transaction.java
- src/test/java/seedu/address/model/person/PersonTest.java
> Transaction

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/model/person/Company.java
- src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
- Minor updates related to Company class
- Update JavaDoc to match new behaviours
- Update class name to match new behaviours
- Update tests on Predicate
> Updates on FindCommand

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/TransactionCard.java
- src/main/java/seedu/address/ui/TransactionListPanel.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/TransactionListCard.fxml
- src/main/resources/view/TransactionListPanel.fxml
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> View transactions gui

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
Fixes #54 and fixes #56 
- Update AddTransactionCommand to use Transaction 
- Add parser for AddTransactionCommand
- Update AddressBookParser to use AddTransactionCommandParser
- Add tests for AddTransactionCommand
- Add tests for AddTransactionCommandParser
> Add parser for AddTransactionCommand

- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- Updates storage for transactions.
- Updates test cases for storage.
- Added sample data for transactions.
Fixes #62
> Transaction storage

- docs/UserGuide.md
> Add `listt` to UG

- docs/UserGuide.md
> Add `addt` command to UG

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
- src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindTransactionCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/TransactionContainsKeywordsPredicate.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/FindTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
- src/test/java/seedu/address/logic/parser/FindTransactionCommandParserTest.java
- src/test/java/seedu/address/model/person/TransactionContainsKeywordsPredicateTest.java
Add `FindTransaction` command.
`findt {personIndex} {keyword} [keywords...]` find all transactions of person `{personIndex}` that match one of the given keywords.
This command should only be used when the current view is the person list since it needs the person index.
TODO:
> Find transaction

- docs/UserGuide.md
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
Keeping separate branch for v1.3 for future reference
> Update release branch

- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/model/person/PersonTest.java
Instead of making users type a command to sum the transactions amounts, I have displayed it in the person card everytime.
Fixes #79
> Add balance to UI

- docs/DeveloperGuide.md
- docs/diagrams/ListTransactionsActivityDiagram.puml
- docs/diagrams/ListTransactionsDiagram.puml
Diagrams added: Sequence diagram, activity diagram
Fixes #82
> Update DG for listt

- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/model/person/TransactionDateComparator.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
Fixes #81 
Update AddTransactionCommand to sort transactions by recency of date
> Sort transactions by date

- docs/DeveloperGuide.md
- docs/diagrams/AddTransactionSequenceDiagram.puml
Fixes #87 
Add sequence diagram for add transaction command.
Update DG with implementation of add transaction command.
> Update DG for `addt` command 

- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
> Bugfix deletet

- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
- src/main/java/seedu/address/model/person/Person.java
Fixed delelet overriding the original transaction list. It should only delete the transaction indicated.
> Fix deletet

- src/main/java/seedu/address/ui/TransactionCard.java
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/TransactionListCard.fxml
Updated GUI:
Fixes #119 , fixes #104
> Improve GUI

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
> Improve find success message

- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
> Update `addt` command to not modify filtered client list 

- src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
- src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
> Improve `listt` messages

- src/main/java/seedu/address/logic/Messages.java
> Update error messages

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
> Update edit command to keep transactions 

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Transaction.java
- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
- src/test/java/seedu/address/model/person/PersonTest.java
> Transaction double

- src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
- src/main/java/seedu/address/logic/parser/ListTransactionCommandParser.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/TransactionCard.java
Adds assertions and logging for `listt`
Fixes #152 , fixes #151 
Updates UI to display amounts and balances in 2dp
Fixes #154
> Increase code quality & Fix amount in UI

- src/main/java/seedu/address/logic/parser/AddressBookParser.java
> Make command words case-insensitive

- src/main/java/seedu/address/model/person/Transaction.java
> Update message constraint for Transaction

- docs/DeveloperGuide.md
- docs/diagrams/AddTransactionSequenceDiagram.puml
> Update DG 

- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/model/person/PersonTest.java
Fixes #143
Reviewer is author of relevant issue
Names are now parsed and autocapitalised according to natural rules, with some room for roman numerals for names like Louis VII. Also handles excess spaces in between words and excess spaces
> Update add for duplicate handling

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
> Update parsing to handle blank inputs for `addt` command

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
- src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
> Update message for attempting `deletet` on empty list

- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/model/person/PhoneTest.java
Fixes #114 
Reviewer is issue's author
Optional fields for country code (1-3 nums) and short note (10 chars)
This fix adds more flexibility to accommodate for better user needs -- mostly to avoid criticisms of p/ being too restrictive
> Update add to handle phone numbers more flexibly

- build.gradle
- docs/site.json
- src/main/java/seedu/address/commons/core/LogsCenter.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/main/resources/view/MainWindow.fxml
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
> Renamed all instances of AB3 to Clientell

- docs/UserGuide.md
> Update UG for `addt`

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
- src/main/java/seedu/address/model/person/Transaction.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
> Update error messages for `addt`

- docs/diagrams/ModelClassDiagram.puml
Update Model UML diagram to include Transaction(s) field for Person
> Update Model diagram for DG

- src/main/java/seedu/address/ui/HelpWindow.java
> Update link to user guide for `help` command

- src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
Storage couldnt store or parse amounts like 100.05, due to it being stored as an int, updated the constructor to be a double.
> Fix storage to store decimals
